name: ci/cd workflow test2

on:
 push:
   branches:
     - main
jobs:
 tests:
   runs-on: ubuntu-latest
   services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33060:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
   strategy:
     matrix:
       php: [7.4]
   name: Test - PHP ${{ matrix.php }}
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Cache PHP dependencies
       uses: actions/cache@v3
       with:
         path: vendor
         key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php }}
         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
         coverage: none
     - name: Install dependencies
       run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
     - name: create data base and env file
       env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 33060
          DB_USER: root
          DB_PASSWORD: password
          DB_DATABASE: sistemas_estado_pago
       run: |
          sudo service mysql start
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword -e 'CREATE DATABASE IF NOT EXISTS sistemas_estado_pago;'
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword -e "SHOW DATABASES;"
     - name: Unzip DB
       uses: montudor/action-zip@v1
       with:
            args: unzip -qq ./bd/sistemas_estado_pago.zip -d ./bd/
     - name: Cargando los datos
       run: |
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword  sistemas_estado_pago < ./bd/sistemas_estado_pago.sql
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword -e "SHOW DATABASES;"
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword sistemas_estado_pago -e "SELECT * FROM estado_pago_usuarios"
     - name: Execute tests
       run: vendor/bin/phpunit --verbose

