name: DOCKER

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33060:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          sudo service mysql start
          mysql -uroot -h127.0.0.1 --port 33060 -e 'CREATE DATABASE IF NOT EXISTS sistemas_estado_pago;'
          mysql -uroot -h127.0.0.1 --port 33060 -e 'CREATE DATABASE IF NOT EXISTS db2;'
          mysql -uroot -h127.0.0.1 --port 33060 -e "SHOW DATABASES;"