name: Unit Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
     matrix:
       php: [7.4]

    name: Test - PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v3
    - name: "instalando mysql"
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
      run: |
        mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS db1;'
        mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS db2;'
        mysql -uroot -h127.0.0.1 -e "SHOW DATABASES;"
    - name: Unzip DB
      uses: montudor/action-zip@v1
      with:
          args: unzip -qq ./sistemas_estado_pago.zip -d