name: DOCKER

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33060:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          sudo service mysql start
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword -e 'CREATE DATABASE IF NOT EXISTS sistemas_estado_pago;'
          mysql -uroot -h127.0.0.1 --port 33060 -ppassword -e "SHOW DATABASES;"
      - name: Unzip DB
        uses: montudor/action-zip@v1
        with:
            args: unzip -qq ./bd/sistemas_estado_pago.zip -d ./bd/
      - name: probando
        run: |
          ls
          ls ./bd
      - name: Cargando los datos
        run: |
          mysql -uroot -h127.0.0.1 sistemas_estado_pago < ./bd/sistemas_estado_pago.sql
          mysql -uroot -h127.0.0.1 -e "SHOW DATABASES;"
          mysql -uroot -h127.0.0.1 -e "SHOW DATABASES;"
          mysql -uroot -h127.0.0.1 sistemas_estado_pago -e "SELECT * FROM estado_pago_usuarios"